nextflow-io/training

asciidocs/awsbatch.adoc, asciidocs/cache_and_resume.adoc, asciidocs/channels.adoc, asciidocs/config.adoc, asciidocs/containers.adoc, asciidocs/debugging.adoc, asciidocs/executors.adoc, asciidocs/groovy.adoc, asciidocs/intro.adoc, asciidocs/modules.adoc, asciidocs/operators.adoc, asciidocs/processes.adoc, asciidocs/rnaseq_pipeline.adoc, asciidocs/setup.adoc, asciidocs/tower.adoc, nf-training/script2.nf, nf-training/script3.nf, nf-training/script4.nf, nf-training/script5.nf, nf-training/script6.nf, nf-training/script7.nf
This Pull Request consists of:
Most of the training code blocks consisted of 4 dashes with [keywords,in,this,format]. Some other times, it used ``` or just indentation.
=> Remove trailing white spaces from script files + fix code/output boxes

.gitpod.yml, gitpod-ws.code-workspace
Start sidebar in nf-training directory
=> SidebarStart

asciidocs/containers.adoc
The MAINTAINER instruction is now deprecated and LABEL should
be used instead.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
=> Replace MAINTAINER by LABEL in Dockerfile examples

asciidocs/containers.adoc
Most of it has been fixed in the past but these two examples remained.
container = 'nextflow-io/rnaseq-nf' when within nextflow.config
container 'nextflow-io/rnaseq-nf' when within script files
=> Equal sign for directives only in config files

CONTRIBUTING.md, mkdocs.yml, requirements.txt
Just until https://github.com/timvink/mkdocs-enumerate-headings-plugin/pull/33 is merged
=> Use fork for numbered headings to fix hands-on numbering

TRANSLATING.md, docs/basic_training/cache_and_resume.md, docs/basic_training/cache_and_resume.pt.md
Hi folks 👋 
I thought that [Resume troubleshooting](https://training.nextflow.io/basic_training/cache_and_resume/#resume-troubleshooting) might be a good place to mention the three cacheing related blogposts.
I was in doubt whether it should be at the end of the content as another point but then I thought, for the curious (or frustrated) folks putting it as a tip might be reasonable.
@mribeirodantas , desculpa que não adiocionei o português - nem tinha certeza que escolhi o lugar certo para adicionar o TIP em inglês. Mas posso fazer isso se vocês concordam mencionar os blogs como um TIP.
=> Add links to cacheing blog posts

docs/basic_training/cache_and_resume.md, docs/basic_training/cache_and_resume.pt.md, docs/basic_training/channels.md, docs/basic_training/channels.pt.md, docs/basic_training/config.md, docs/basic_training/config.pt.md, docs/basic_training/containers.md, docs/basic_training/containers.pt.md, docs/basic_training/executors.md, docs/basic_training/executors.pt.md, docs/basic_training/groovy.md, docs/basic_training/groovy.pt.md, docs/basic_training/intro.md, docs/basic_training/intro.pt.md, docs/basic_training/modules.md, docs/basic_training/modules.pt.md, docs/basic_training/operators.md, docs/basic_training/operators.pt.md, docs/basic_training/processes.md, docs/basic_training/processes.pt.md, docs/basic_training/rnaseq_pipeline.md, docs/basic_training/rnaseq_pipeline.pt.md, nf-training/modules.hello.nf, nf-training/script3.nf
- Improve placement of + helpers in source code examples
- Add/remove spaces when required to make its usage consistent
- Sync Portuguese translations of the basic training material
=> Improve syntax consistency of training material

docs/basic_training/cache_and_resume.md, docs/basic_training/cache_and_resume.pt.md, docs/basic_training/channels.md, docs/basic_training/channels.pt.md, docs/basic_training/config.md, docs/basic_training/config.pt.md, docs/basic_training/containers.md, docs/basic_training/containers.pt.md, docs/basic_training/executors.md, docs/basic_training/executors.pt.md, docs/basic_training/index.md, docs/basic_training/index.pt.md, docs/basic_training/intro.md, docs/basic_training/intro.pt.md, docs/basic_training/modules.md, docs/basic_training/modules.pt.md, docs/basic_training/processes.pt.md, docs/basic_training/rnaseq_pipeline.md, docs/basic_training/rnaseq_pipeline.pt.md, docs/basic_training/tower.md, docs/basic_training/tower.pt.md, docs/index.md, docs/index.pt.md
- Fix usage of image name and image tag
- Name them channel operator/factory instead of "method"
- Sync Portuguese translation
=> Make terminology consistent in the basic training

docs/basic_training/channels.md, docs/basic_training/channels.pt.md, docs/basic_training/debugging.md, docs/basic_training/debugging.pt.md, docs/basic_training/executors.md, docs/basic_training/intro.md, docs/basic_training/intro.pt.md, docs/basic_training/modules.pt.md, docs/basic_training/operators.md, docs/basic_training/operators.pt.md, docs/basic_training/processes.md, docs/basic_training/processes.pt.md, docs/basic_training/rnaseq_pipeline.md, docs/basic_training/rnaseq_pipeline.pt.md
- Make usage of process/task/job consistent
- Make line splitting consistent for chained operators
- Sync Portuguese translation
=> Make usage of task/job/process consistent

docs/basic_training/rnaseq_pipeline.pt.md
Source code in script file was translated, but this is specifically
the exception when we shouldn't translate, that is, when there is a
script file with the source code (so that we don't have multiple
source code files, one for each language).
=> Revert Portuguese translation in RNAseq section of the basic training

docs/basic_training/channels.md, docs/basic_training/channels.pt.md, mkdocs.yml
- Update JSON section in basic training
- Update Portuguese translation of Channel section in basic training
=> Update JSON subsection

docs/basic_training/processes.md, docs/basic_training/processes.pt.md
In the first Warning section of the "process" page in the "basic train", I made changes to the statement: "**Since Nextflow uses the same Bash syntax for variable substitutions in strings, Bash environment variables need to be escaped using the \ character.**" 
I felt the explanation wasn't very clear, so I added the following content: "**When you use a \, the $PWD is a directory that Nextflow creates for that specific process (e.g. work/7f/f285b80022d9f61e82cd7f90436aa4/).**"
=> Clarified Explanation in the "Warning" Section of the Process Page

docs/basic_training/processes.md, docs/basic_training/processes.pt.md
Instead of **< sample1.fq.gz zcat > sample1.fq**, **using zcat sample1.fq.gz > sample1.fq** is a more common and intuitive method to decompress a gzip file. This approach is more standard and easier to understand.
Using < sample1.fq.gz zcat > sample1.fq is unnecessary and could lead to confusion. In fact, this usage might not work properly in certain cases, as not all versions of zcat support reading from standard input.
=> A more consistent code style

docs/hands_on/02_workflow.md, docs/hands_on/03_setup.md, docs/hands_on/04_implementation.md, hands-on/final_main.nf, mkdocs.yml
=> Update hands-on workshop to DSL2

docs/hands_on/02_workflow.md, docs/hands_on/03_setup.md, docs/hands_on/04_implementation.md, docs/hands_on/index.md, hands-on/final_main.nf, hands-on/nextflow.config
This PR intends to update the hands-on training to follow the best practices, i.e. to have a light container image for every process.
=> Update hands-on training to use multiple container images

mkdocs.yml, requirements.txt
- Fix mkdocs.yml to the format of the new version of i18n plugin
- Pin versions of mkdoc related python packages
=> Fix mkdocs breaking version

docs/hands_on/04_implementation.md, hands-on/final_main.nf
Hi,
In the hands-on training, the process `rnaseq_call_variants` is meant to be executed at the sample level (as documented in problem 9 https://training.nextflow.io/hands_on/04_implementation/#process-5-gatk-variant-calling), but instead executed at the replicate level. 
This results in 2 `final.vcf` files produced in 1 sample, and 1 of vcf would be selected and used in the final step (ASE_knownSNPs process).
This error can be spotted in the expected output section (https://training.nextflow.io/hands_on/04_implementation/#bonus-step), where `rnaseq_call_variants ` is executed 6 times but not 3 times.
A fix for this is to do a `groupTuble` on the `rnaseq_gatk_recalibrate.out` channel and before feeding it to `rnaseq_call_variants`
=> Fix issue on process rnaseq_call_variants not executed at sample level in hands-on training materials

docs/hands_on/03_setup.md, docs/hands_on/04_implementation.md, docs/hands_on/index.md, hands-on/final_main.nf
=> Improve hands-on training

docs/advanced/structure.md
Just a small typo in the advanced tutorial.
=> Fix typo Kyro to Kryo

docs/basic_training/setup.md
_And put the `nextflow` executable into your `$PATH` (e.g. `/usr/local/bin` or `/bin/`)_
becomes
_And put the `nextflow` executable into your `$PATH`. The executable could be in `/usr/local/bin`, `/bin/`, etc._
=> Refactor: Rewording sentence for more clarity in Basic Training Setup.

docs/basic_training/index.md, docs/basic_training/operators.md, docs/basic_training/processes.md
This PR fixes three very small erroneous references:
- Welcome: Changed Nextflow tower to Seqera Platform
- Opeartors: Fixed missreferencing of `splitText()` and added `splitCsv()` header
- Processes: Fixed wrong referencing to snippet above when it was the snippet below
Two additional things:
1) `publishDir` gets asked for in an exercise before its introduced. Is this wanted?
2) The gitpod for the training doesn't have singularity, but in general, singularity can work in Gitpod. This [statement](https://github.com/nextflow-io/training/blob/2cd5a8c32919cf6e4bd4f198e378cc57417bac3e/docs/basic_training/containers.md?plain=1#L333) in Dependencies and containers sections makes it sound as if singularity can't work in Gitpod at all. Any reason singularity is not included in the Gitpod image? …
=> Fixing minor errors

docs/basic_training/rnaseq_pipeline.md
When conducting the training in the previous two sessions, I felt these points felt out of place or kind of already giving out the answer for the exercises (exercises that are already quite easy to begin with 😆).
=> Apply minor changes to improve RNAseq section

docs/basic_training/processes.md, docs/basic_training/processes.pt.md, docs/hands_on/04_implementation.md, docs/hello_nextflow/03_hello_gatk.md, docs/hello_nextflow/04_hello_modules.md, docs/hello_nextflow/05_hello_nf-test.md, docs/troubleshoot/06_exercise.md, hands-on/final_main.nf, hello-nextflow/hello-modules.nf, hello-nextflow/scripts/hello-gatk-1.nf, hello-nextflow/scripts/hello-gatk-2.nf, hello-nextflow/scripts/hello-gatk-3.nf, hello-nextflow/scripts/hello-gatk-4.nf, hello-nextflow/scripts/hello-gatk-5.nf, hello-nextflow/scripts/hello-gatk-6.nf, hello-nextflow/scripts/nextflow.config, mkdocs.yml, troubleshoot/exercise1/hello-gatk.nf, troubleshoot/exercise2/hello-gatk.nf, troubleshoot/exercise3/hello-gatk.nf, troubleshoot/exercise4/hello-gatk.nf, troubleshoot/exercise5/hello-gatk.nf, troubleshoot/exercise6/hello-gatk.nf, troubleshoot/hello-gatk.nf
=> Fix #336 baseDir -> projectDir, from -> of

docs/basic_training/executors.md
Addresses a missing detail about hybrid deployments and using `-bucket-dir` to specify a path to remote object storage required as the work directory for all cloud executor jobs, in addition to a local path through `-work-dir` for locally executed jobs. 
This is mentioned in the CLI details in Nextflow docs [here](https://www.nextflow.io/docs/latest/cli.html).
=> docs: add bucket-dir param details for hybrid deployment

docs/basic_training/operators.md
Just fixing a glitch that I think might have come from a previous update, which removed the 'CSV files outside the channel context' example.
=> Fix inconsistency in basic operators coverage

docs/advanced/configuration.md
1. There is no 'configuration' directory
2. A `withLabel` example probably needs to be a `withName`
=> Update configuration.md for minor errors

docs/basic_training/cache_and_resume.md
A couple of fixes:
- Dollar signs are unhelpful in command blocks (they have to be removed by anyone copying/ pasting the blocks)
- Final example is hard to talk through, because it's incomplete- suggesting a fix
In that final example the 'solution' part does not match the 'problem' part, which makes it hard to follow. There's also a lot of 'imagining' required. I've made a simpler, more complete example for both.
=> Fixes for cache_and_resume.md

docs/basic_training/containers.md
I don't feel like it's a productive use of people's time to dig in biocontainers for an image, can we just provide them in the final exercise here?
=> Don't make learners dig in Biocontainers

docs/basic_training/processes.md
Currently, the command example here is jarring, it fails with an error with no explanation. The correct form is cited below, we should just warn the user that the failure was intentional.
=> make clear that specific output channel must be specified for view()

docs/basic_training/containers.md
I'm just proposing that we allow people to jump in here, without building their own images.
=> Update containers.md with example public image

docs/basic_training/containers.md
Two minor fixes:
- First containers example should not contain 'cowsay' since that's the objective of the following exercise.
- Use literal 'my-image' rather than '<my-image>' all the way through. Right now we do it later on, but not at first, which makes things hard to follow.
=> Minor fix to containers

.gitpod.yml, README.md, docs/advanced/index.md, docs/basic_training/index.md, docs/envsetup/index.md, docs/hello_nextflow/index.md, docs/help.md, docs/index.md, docs/nf_customize/index.md, docs/nf_develop/index.md, docs/troubleshoot/index.md, gitpod-ws.code-workspace, mkdocs.yml
**Gitpod**
- Switch default work directory to Hello Nextflow
- Also open the Hello Nextflow training page in the simple browser
- Reorder how the trainings are listed in the file explorer in gitpod
- Hide the hands-on training directory in the gitpod (deprecating it)
**Website**
- Reorganized order of courses + tweaked language on the training portal
- Updated language and links in Readme, Help
=> Update gitpod defaults + training portal home page and related

docs/basic_training/groovy.md, docs/basic_training/groovy.pt.md
Fixes this error in [basic training doc](https://training.nextflow.io/basic_training/groovy/#if-statement), where snippet.nf does not generate the Output:
- Corrected If statement snippet in groovy.md, so that code gives the result shown in the Output block
- Updated If statement snippet in groovy.pt.md, to match the updated code in groovy.md
- Added missing output code block to If statement example in groovy.pt.md, to match the output code block in groovy.md
=> Correction for groovy If statement snippet

.devcontainer/devcontainer.json
This PR adds support for a devcontainer which allows docker-outside-docker, therefore users can run hello-genomics etc.
The only limitation so far is the paths in the samplesheet don't match (`/workspace/gitpod/`), I've tried to fix it but no luck so far. We could add this right now to provide a backup before we solve the gitpod absolute path problem in the repository.
=> devcontainer support with docker-outside-docker

docs/hello_nextflow/01_orientation.md
Very minor, no functional changes
=> Updates to the wording and tree output

docs/hello_nextflow/01_orientation.md, docs/hello_nextflow/03_hello_containers.md, docs/hello_nextflow/07_hello_modules.md, docs/hello_nextflow/08_hello_nf-test.md, docs/hello_nextflow/09_hello_nf-core.md, docs/hello_nextflow/seqera/02_run_with_launchpad.md
No code changes, just text fixes. Safe to merge.
=> Fix minor typos on Hello Nextflow

docs/hello_nextflow/01_orientation.md, docs/hello_nextflow/02_hello_world.md, docs/hello_nextflow/04_hello_genomics.md
- **Fix tree output in orientation (Part 1)**
- **Replace channel constructor with channel factory**
=> minor fixes

docs/hello_nextflow/04_hello_genomics.md, docs/hello_nextflow/05_hello_operators.md, docs/hello_nextflow/07_hello_modules.md, hello-nextflow/hello-config/main.nf, hello-nextflow/hello-modules/main.nf, hello-nextflow/hello-nf-test/modules/local/gatk/haplotypecaller/main.nf, hello-nextflow/hello-nf-test/modules/local/gatk/jointgenotyping/main.nf, hello-nextflow/hello-operators.nf, hello-nextflow/solutions/hello-config/final-main.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-2.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-3.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-4.nf, hello-nextflow/solutions/hello-modules/modules/local/gatk/GATK_HAPLOTYPECALLER/main.nf, hello-nextflow/solutions/hello-modules/modules/local/gatk/GATK_JOINTGENOTYPING/main.nf, hello-nextflow/solutions/hello-nf-test/modules/local/gatk/haplotypecaller/main.nf, hello-nextflow/solutions/hello-nf-test/modules/local/gatk/jointgenotyping/main.nf, hello-nextflow/solutions/hello-operators/hello-operators-1.nf, hello-nextflow/solutions/hello-operators/hello-operators-2.nf, hello-nextflow/solutions/hello-operators/hello-operators-3.nf
Suggest we use `emit:` on the multi outputs so participants done't think they'r stuck with `FOO.out[0]`.
=> Add emits to outputs of processes with multiple outputs

docs/hello_nextflow/02_hello_world.md
Tiny thing- the 'before' string in this example is wrong wrt previous actions.
=> Update 02_hello_world.md to correct a 'before' string

.devcontainer/devcontainer.json
```
$ export NXF_HOME=/workspaces/.nextflow
gitpod /workspaces/training (master) $ nextflow -v
/opt/conda/bin/mkdir: cannot create directory ‘/workspaces/.nextflow’: Permission denied
/opt/conda/bin/mkdir: cannot create directory ‘/workspaces/.nextflow’: Permission denied
```
```
$ export NXF_HOME=/workspaces/training/.nextflow
gitpod /workspaces/training (master) $ nextflow -v
...
CAPSULE: Downloading dependency com.fasterxml.jackson.core:jackson-core:jar:2.16.1
CAPSULE: Downloading dependency org.iq80.leveldb:leveldb:jar:0.12
CAPSULE: Downloading dependency org.apache.groovy:groovy:jar:4.0.19
nextflow version 24.02.0-edge.5907       
```
=> Update devcontainer.json to set NXF_HOME to writable path

docs/hello_nextflow/02_hello_world.md
I think the current usage of flatten here is confusing without a bit of explanation.
=> Better describe use of flatten

.devcontainer/devcontainer.json
This fix resolves an issue where Gitpod was mounting the repository at `/workspaces/workspaces/training`, which causes issues with the Docker mounting. 
This change in the devcontainers.json mounts the training material at the same location in the container as it exists in the host, which ensures that mount paths to docker when run inside the container also resolve in the host.
=> More specific workspaceMounts for devcontainer

docs/hello_nextflow/04_hello_genomics.md, docs/hello_nextflow/05_hello_operators.md, docs/hello_nextflow/06_hello_config.md, docs/hello_nextflow/07_hello_modules.md, hello-nextflow/hello-config/demo-params.json, hello-nextflow/hello-config/main.nf, hello-nextflow/hello-modules/demo-params.json, hello-nextflow/hello-modules/main.nf, hello-nextflow/hello-modules/nextflow.config, hello-nextflow/hello-nf-test/demo-params.json, hello-nextflow/hello-nf-test/modules/local/gatk/haplotypecaller/main.nf, hello-nextflow/hello-nf-test/modules/local/gatk/jointgenotyping/main.nf, hello-nextflow/hello-nf-test/modules/local/samtools/index/main.nf, hello-nextflow/hello-nf-test/nextflow.config, hello-nextflow/hello-operators.nf, hello-nextflow/solutions/hello-config/final-main.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-1.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-2.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-3.nf, hello-nextflow/solutions/hello-genomics/hello-genomics-4.nf, hello-nextflow/solutions/hello-modules/modules/local/gatk/GATK_HAPLOTYPECALLER/main.nf, hello-nextflow/solutions/hello-modules/modules/local/gatk/GATK_JOINTGENOTYPING/main.nf, hello-nextflow/solutions/hello-modules/modules/local/samtools/index/main.nf, hello-nextflow/solutions/hello-nf-test/modules/local/gatk/haplotypecaller/main.nf, hello-nextflow/solutions/hello-nf-test/modules/local/gatk/jointgenotyping/main.nf, hello-nextflow/solutions/hello-nf-test/modules/local/samtools/index/main.nf, hello-nextflow/solutions/hello-operators/hello-operators-1.nf, hello-nextflow/solutions/hello-operators/hello-operators-2.nf, hello-nextflow/solutions/hello-operators/hello-operators-3.nf
Training participants during summit highlighted that the `outdir` in the nf-test part had no effect. That's because the workflow didn't have an outdir parameter.
I've removed the hardcoded publishDir back as far as 'hello genomics'.
=> Add an outdir parameter for 'hello genomics' onwards

docs/hello_nextflow/03_hello_containers.md, docs/hello_nextflow/04_hello_genomics.md
This is a fudge, but while we transition to GitPod Flex/ devcontainers, it would be helpful in the first instance if we didn't direct users to do breaking 'cd' operations.
While we have symlinked the alternative gitpod location in https://github.com/nextflow-io/training/pull/462, working within those symlinks will not work (e.g. paths are not valid when we do docker-outside-docker). 
So it would be good if we kept the instructions more generic.
=> Make cd less specific

.devcontainer/devcontainer.json
Symlink to required so that paths in the materials that expect the Gitpod (classic) paths still resolve in devcontainers.
In the medium term, we should remove paths and that are specific to the original Gitpod implementation.
=> Adjust paths so that Gitpod (original) mounting points 

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, docs/hello_nextflow/02_hello_world.md, docs/hello_nextflow/04_hello_genomics.md, docs/hello_nextflow/05_hello_operators.md, docs/hello_nextflow/06_hello_config.md, docs/hello_nextflow/07_hello_modules.md, docs/hello_nextflow/08_hello_nf-test.md
I would argue that training should not be done on an edge version of Nextflow. This was originally set so that we could get early access to Phil's very fancy coloured outputs. This feature has been in stable Nextflow for some time, so we can safely move to a stable version of Nextflow.
This will also (temporarily) prevent the ugly message about a new Nextflow version on every run.
=> Update Nextflow version to latest stable (24.10.0)

docs/hello_nextflow/05_hello_operators.md
Bit of mop-up after https://github.com/nextflow-io/training/pull/437
=> Correct hangover from before we added all the script:

hello-nextflow/hello-modules/nextflow.config, hello-nextflow/hello-nf-test/nextflow.config, hello-nextflow/solutions/hello-config/5-nextflow.config
Parameters were being read as defaults instead of the profile `demo` which was causing problems. This PR moves them to the right location.
=> Move parameters to above profiles for correct handling of params

hello-nextflow/hello-config/main.nf, hello-nextflow/hello-modules/main.nf, hello-nextflow/hello-nf-test/main.nf, hello-nextflow/solutions/hello-config/final-main.nf, hello-nextflow/solutions/hello-modules/final-main.nf, hello-nextflow/solutions/hello-operators/hello-operators-2.nf, hello-nextflow/solutions/hello-operators/hello-operators-3.nf
Some previous outputs of GATK_HAPLOTYPECALLER were still integer based instead of named. This PR replaces them.
=> Replace numeric with named outputs for GATK_HAPLOTYPECALLER

docs/hello_nextflow/08_hello_nf-test.md
There is an additional curly bracket in hello-nf-test. This removes it.
=> Additional curly bracket in hello-nf-test doc

docs/hello_nextflow/seqera/01_run_with_cli.md
This includes tweaks to the instructions for using the TOWER_ACCESS_TOKEN so users don't need to rely on leaving a browser tab open.
=> docs (hello-seqera): use env variable for saving token

.gitpod.yml, docs/hello_nextflow/09_hello_nf-core.md
Tweak materials to view the assets folder correctly in hello-nf-core.
I've set NXF_HOME in the Gitpod config so we can do something consistent with devcontainers.
=> Better handle assets dir in nf-core section

.github/workflows/release-docs.yml, requirements.txt
Should run whenever a new GitHub release is published.
Based largely on https://github.com/squidfunk/mkdocs-material/discussions/4759#discussioncomment-4405468 plus my own local expiermentation.
=> Add GitHub action to publish new docs on GitHub Release

docs/index.es.md, docs/index.fr.md, docs/index.md, docs/index.pt.md, mkdocs.yml
Stacked on top of https://github.com/nextflow-io/training/pull/486
One-line change to remove `- navigation.tabs` from `mkdocs.yml` so that we can see how the nav would look without the Navigation Tabs top-nav.
=> No nav tabs

.github/workflows/docker.yml, docs/envsetup/01_setup.md, docs/envsetup/index.md, docs/hello_nextflow/00_orientation.pt.md, docs/hello_nextflow/03_hello_workflow.md, docs/hello_nextflow/05_hello_containers.md, docs/nextflow_run/03_run_nf-core.md
- **Fix capitalization of GitHub and Gitpod**
- **Minor fixes to Part 3**
- **Part 4** is very good, but a bit short.
- **Minor fixes to Part 5**
=> Minor fixes to parts 3, 4, and 5 of Hello Nextflow

docs/hello_nextflow/06_hello_config.md, docs/hello_nextflow/07_next_steps.md, docs/hello_nextflow/next_steps.md, docs/hello_nextflow/survey.md, mkdocs.yml
Add end page for the trainings with links to further resources + an embedded survey to collect feedback.
Addresses https://github.com/nextflow-io/training/issues/522
=> Add Next Steps page with survey

docs/hello_nextflow/02_hello_channels.md, docs/hello_nextflow/03_hello_workflow.md, docs/hello_nextflow/05_hello_containers.md
Some minor fixes for things that I spotted whilst recording the new training. I made these edits locally before recording, so they are included in the video footage already.
The main change was removing use of the implicit `$it` variable. See https://nextflow.io/docs/latest/updating-syntax.html#deprecated-syntax for details:
=> Training small fixes

docs/assets/overrides/main.html, mkdocs.yml
Use some Javascript to automatically hide the announcement banner if a specified date has passed.
Means that we can still have the banner active even in fixed statically built releases.
Downside is that there is a slight flicker on page load for the banner, I can't get around that though. I've prioritised the flicker for when it's active, vs. when it's inactive (figure it'll be inactive more of the time).
=> Hide announcement with JS if date is past

docs/hello_nextflow/01_hello_world.md
For consistency's sake. (Although they look off anyway (too LaTeXy), imo)
=> add missing trailing periods

.github/workflows/devcontainer-build-and-push.yml
Hotfix for https://github.com/nextflow-io/training/pull/569 - the image build + push did not push:
https://github.com/nextflow-io/training/actions/runs/13954931238/job/39063529578
```
Post job cleanup.
Image push skipped because GITHUB_EVENT_NAME (push) is not in eventFilterForPush
```
Doing some searches on GitHub finds [this](https://github.com/trxcllnt/devcontainers-ci/blob/be3fd68d800b48cf9a78571fe318c53bfd42aa88/.github/workflows/ci_common.yml#L472-L474), so I guess it needs to split by newlines instead of commas. Undocumented, but trying anyway.
=> devcontainers/ci build+push - split by newline not comma for `eventFilterForPush`

.devcontainer/devcontainer.json, .devcontainer/setup.sh
This should avoid the 
```
WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/viralrecon/illumina/amplicon/sample2_R1.fastq.gz (try 1 of 3) -- Cause: No PSK available. Unable to resume.
```
error
I tested this on a codespace generated with that branch, and the warning is gone
=> Add tls client environment variable

docs/nf4_science/genomics/02_joint_calling.md, docs/nf4_science/genomics/04_testing.md
Tiny tweaks in response to training delivery today:
1. Add some highlights where code blocks illustrate changes
2. Reinforce renames of tests and add a name to the workflow test to distinguish it in the final collected tests
3. Correct nf-test config path in a block
=> Post training tweaks

CONTRIBUTING.md, README.md
Realised that I shouldn't really have put these in the main readme. Moved to contributing and added a more obvious note admonition on the readme to point to this file.
=> Move check-headings docs to `CONTRIBUTING.md`

docs/hello_nextflow/01_hello_world.md, docs/hello_nextflow/02_hello_channels.md, docs/hello_nextflow/03_hello_workflow.md, docs/hello_nextflow/04_hello_modules.md, docs/hello_nextflow/05_hello_containers.md, docs/hello_nextflow/06_hello_config.md, hello-nextflow/hello-containers.nf
- **Update outputs**
- **Update script to resemble training content**
=> small fixes to outputs
