- README.md
- asciidocs/setup.adoc
- nf-training/hello.nf
> Final changes 22 mar2022

- asciidocs/cache_and_resume.adoc
- asciidocs/intro.adoc
- asciidocs/modules.adoc
- asciidocs/operators.adoc
- asciidocs/processes.adoc
- asciidocs/setup.adoc
Fix typos and correct a few English sentences. This pull request is related to https://github.com/seqeralabs/nf-training-public/pull/82.
> Improve English

- asciidocs/rnaseq_pipeline.adoc
- nf-training/script1.nf
- nf-training/script2.nf
- nf-training/script3.nf
- nf-training/script4.nf
- nf-training/script5.nf
- nf-training/script6.nf
- nf-training/script7.nf
> Script updates

- asciidocs/modules.adoc
Checked all code. All but one block working
> Modules capitals

- asciidocs/intro.adoc
> Fix small typos

- asciidocs/containers.adoc
- Update env.yml for conda environment
- Update micromamba section
> Update section on Conda / Micromamba

- asciidocs/containers.adoc
> Expand the BioContainers subsection with examples

- asciidocs/awsbatch.adoc
- asciidocs/cache_and_resume.adoc
- asciidocs/channels.adoc
- asciidocs/config.adoc
- asciidocs/containers.adoc
- asciidocs/debugging.adoc
- asciidocs/executors.adoc
- asciidocs/groovy.adoc
- asciidocs/intro.adoc
- asciidocs/modules.adoc
- asciidocs/operators.adoc
- asciidocs/processes.adoc
- asciidocs/rnaseq_pipeline.adoc
- asciidocs/setup.adoc
- asciidocs/tower.adoc
- asciidocs/welcome.adoc
- Update mentions to the file keyword in multiple sections
- Update fromSRA example
- Update processes section
- Fix typos
- Remove trailing whitespaces
> Update training material (DSL2, among other things)

- asciidocs/processes.adoc
> Fixes #107: Directives declaration

- README.md
- asciidocs/cache_and_resume.adoc
- asciidocs/channels.adoc
- asciidocs/containers.adoc
- asciidocs/executors.adoc
- asciidocs/groovy.adoc
- asciidocs/modules.adoc
- asciidocs/rnaseq_pipeline.adoc
- asciidocs/setup.adoc
- asciidocs/tower.adoc
- asciidocs/welcome.adoc
- Fix minor typo and trailing white spaces in README
- Fix minor typos in the training material
- Replace Ciao by Olá in example with params
> Minor fixes

- asciidocs/intro.adoc
Punctuation and grammar fixes to intro.adoc .
> Adocs fixes: section 2

- asciidocs/channels.adoc
- asciidocs/processes.adoc
- Update file extension for YAML parsing example
- Update channel factory for example 6.3.4
- Improve wording for single script block in the process
- Remove repeated subsection for file/path
- Improves Value Channel subsection
> Minor improvements

- asciidocs/awsbatch.adoc
> Remove repeated words in the AWS Batch section

- .github/workflows/docker.yml
- .gitpod.yml
- README.md
- docs/assets/overrides/partials/toc.html
- docs/basic_training/channels.md
- docs/basic_training/containers.md
- docs/basic_training/rnaseq_pipeline.md
- docs/basic_training/setup.md
- docs/index.md
- mkdocs.yml
From `seqeralabs/nf-training-public` to `nextflow-io/training`
> Rename repository after move

- docs/basic_training/setup.md
- docs/basic_training/setup.pt.md
- mkdocs.yml
> Translate to Brazilian Portuguese the setup section of the basic training

- TRANSLATING.md
> Create TRANSLATING.md file with instructions

- docs/basic_training/operators.pt.md
- mkdocs.yml
- Update mkdocs config
- Create pt version of the operators section
> Translate to Brazilian Portuguese the operators section of the basic training

- docs/basic_training/intro.pt.md
> Translate to Brazilian Portuguese the introduction section of the basic training

- .github/mkdocs.Dockerfile
> Update mkdocs Dockerfile to install i18n plugin (#176)

- TRANSLATING.md
> Add note about translating words related to keywords

- docs/basic_training/channels.pt.md
> Translate to Brazilian Portuguese the channels section of the basic training

- docs/basic_training/config.md
> Fix missing line in the config section of the basic training

- docs/basic_training/config.pt.md
Added first version for config.
Review translation and add example for conda config.
> Translate to Brazilian Portuguese the config section of the basic training

- TRANSLATING.md
> Add instructions on how to merge translations

- docs/basic_training/modules.pt.md
This is a first version for modules translation to brazilian Portuguese (https://github.com/nextflow-io/training/issues/190).
> Translate to Brazilian Portuguese the modules section of the basic training

- docs/basic_training/channels.md
- docs/basic_training/config.md
- docs/basic_training/containers.md
- docs/basic_training/executors.md
- docs/basic_training/groovy.md
- docs/basic_training/intro.md
- docs/basic_training/modules.md
- docs/basic_training/processes.md
- docs/basic_training/setup.md
- docs/basic_training/tower.md
This pull request consists of several small updates/fixes to the training material, including syntax mistakes, typos/rewording, and improving/updating examples and fixing links.
> Improve basic training material through minor fixes

- docs/basic_training/channels.pt.md
- docs/basic_training/config.pt.md
- docs/basic_training/containers.pt.md
- docs/basic_training/executors.pt.md
- docs/basic_training/groovy.pt.md
- docs/basic_training/intro.pt.md
- docs/basic_training/modules.pt.md
- docs/basic_training/processes.pt.md
- docs/basic_training/setup.pt.md
- docs/basic_training/tower.pt.md
According to https://github.com/nextflow-io/training/pull/198
> Update Portuguese translation of the basic training content

- docs/basic_training/cache_and_resume.md
- docs/basic_training/cache_and_resume.pt.md
> Add meta map example to the cache section of the basic training

- docs/basic_training/channels.md
- docs/basic_training/channels.pt.md
- docs/basic_training/containers.md
- docs/basic_training/containers.pt.md
- docs/basic_training/debugging.pt.md
- docs/basic_training/groovy.md
- docs/basic_training/groovy.pt.md
- docs/basic_training/operators.pt.md
- docs/basic_training/processes.md
- docs/basic_training/processes.pt.md
- Update/correct minor mistakes in the container section
- Sync Portuguese translation of the container section
- Update/correct minor mistakes in the channels section
- Sync Portuguese translation of the channels section
- Update/correct minor mistakes in the container section
- Sync Portuguese translation of the container section
- Correct a minor mistake in the Portuguese version of the operator section
- Correct a minor mistake in the groovy section
- Sync Portuguese translation of the groovy section
- Correct a minor mistake in the Portuguese translation of the debugging section
> fixes basic training (first part)

- docs/basic_training/cache_and_resume.md
- docs/basic_training/cache_and_resume.pt.md
- docs/basic_training/channels.md
- docs/basic_training/channels.pt.md
- docs/basic_training/config.md
- docs/basic_training/config.pt.md
- docs/basic_training/debugging.md
- docs/basic_training/debugging.pt.md
- docs/basic_training/executors.md
- docs/basic_training/executors.pt.md
- docs/basic_training/groovy.md
- docs/basic_training/groovy.pt.md
- docs/basic_training/intro.md
- docs/basic_training/intro.pt.md
- docs/basic_training/modules.md
- docs/basic_training/modules.pt.md
- docs/basic_training/operators.md
- docs/basic_training/operators.pt.md
- docs/basic_training/processes.md
- docs/basic_training/processes.pt.md
- docs/basic_training/rnaseq_pipeline.md
- docs/basic_training/rnaseq_pipeline.pt.md
- docs/basic_training/tower.md
- docs/basic_training/tower.pt.md
- Convert all process names to uppercase
- Add consistency to spacing around keywords and symbols
- Keep the whole training on the same Nextflow version
- Make indentation and new lines in process blocks consistent
- Sync Portuguese translation of the basic training
> Several improvements on the basic training

- docs/basic_training/processes.md
- docs/basic_training/processes.pt.md
- Fix example with tuples
- Update Portuguese translation of the basic training
> Fix tuple definition in example (Process section)

- docs/basic_training/processes.md
- docs/basic_training/processes.pt.md
- Match exercise solution to code mentioned earlier
- Sync Portuguese translation of the basic training (Process section)
> Fix snippet to match exercise in process section

- docs/basic_training/tower.fr.md
docs/basic_training/tower.fr.md
> Translation of Training documentation in french

- docs/basic_training/channels.pt.md
> Update Portuguese translation of YAML subsection

- docs/basic_training/cache_and_resume.fr.md
- docs/basic_training/cache_and_resume.md
- docs/basic_training/cache_and_resume.pt.md
- Improve mention of the fair directive in the cache subsection
- Update Portuguese and French translation of the cache section
> Improve description of the fair process directive

- docs/basic_training/index.md
> Add links to the recordings in the basic training welcome page

- docs/basic_training/index.es.md
- docs/basic_training/index.fr.md
- docs/basic_training/index.pt.md
- Update pt translation of welcome section in basic training
- Update es translation of welcome section in basic training
- Update fr translation of welcome section in basic training
> update translations basictraining

- docs/index.es.md
- docs/index.fr.md
- docs/index.md
- docs/index.pt.md
- Update note on hands-on training
- Update pt/es/fr translation of note in hands-on training
> Update note on Hands-on training

- docs/hands_on/04_implementation.md
> Improve Markdown annotations for handson training

- docs/basic_training/containers.md
- docs/basic_training/containers.pt.md
> Update containers.md with multi-tool images link in BioContainers

- docs/hands_on/03_setup.md
- gitpod-ws.code-workspace
> Add instructions for Gitpod on hands-on training

- docs/basic_training/channels.md
- docs/basic_training/channels.pt.md
- docs/basic_training/config.md
- docs/basic_training/config.pt.md
- docs/basic_training/containers.md
- docs/basic_training/containers.pt.md
- docs/basic_training/processes.md
- docs/basic_training/processes.pt.md
- docs/basic_training/rnaseq_pipeline.fr.md
- docs/basic_training/rnaseq_pipeline.md
- docs/basic_training/rnaseq_pipeline.pt.md
- Add missing space after commas
- Make labels for solution dropdown consistent
> Small fixes to basic training

- docs/basic_training/index.es.md
- docs/basic_training/index.fr.md
- docs/basic_training/index.md
- docs/basic_training/index.pt.md
Please, approve, when ready, so that I can update the other languages _BEFORE_ merging the PR.
> Add most recent training recording playlist to basic training

- docs/hands_on/04_implementation.md
- Convert comments + fix instructions in process 1A
- Convert comments + fix instructions in process 1C/1D
- Convert comments + fix instructions in process 2
- Convert comments + fix instructions in process 3
- Convert comments + fix instructions in process 4
- Fix indenting of (+) comments
- Convert comments + fix instructions in process 5
- Minor indent fix
> Convert comments hands-on + small fixes

- docs/advanced/configuration.md
Signed-off-by: Rob Syme <rob.syme@gmail.com>
> Updated Configuration chapter

- docs/basic_training/containers.md
- docs/basic_training/debugging.md
- docs/basic_training/executors.md
- docs/basic_training/groovy.md
- docs/basic_training/intro.md
- docs/basic_training/operators.md
- docs/basic_training/processes.md
- docs/basic_training/rnaseq_pipeline.md
> Improve foundational

- docs/index.md
- mkdocs.yml
- Updated index layout and header
> Update index layout

- docs/advanced/support.md
Improve support page on Advanced Training with instructions for help.
> Improve support page on Advanced Training

- docs/hands_on/03_setup.md
Also:
* Linked to documentation RE bundling executables
* Moved chmod instructions up as subsection, to keep things together
Fixes #303
> Made bin script more explicit in setup in RNASeq work through

- CONTRIBUTING.md
- docs/assets/overrides/main.html
- docs/assets/stylesheets/extra.css
- mkdocs.yml
Made it customisable via the `mkdocs.yml` config, as I figure we'll want this banner fairly regularly. See `CONTRIBUTING.md` for usage.
> Add announcement banner for upcoming training event

- docs/basic_training/cache_and_resume.md
- docs/basic_training/channels.md
- docs/basic_training/config.md
- docs/basic_training/containers.md
- docs/basic_training/executors.md
- docs/basic_training/index.md
- docs/basic_training/modules.md
- docs/basic_training/operators.md
- docs/basic_training/processes.md
- docs/basic_training/rnaseq_pipeline.md
- docs/basic_training/setup.md
- docs/index.md
- mkdocs.yml
> Rename Foundational training to Fundamentals

- .github/gitpod.Dockerfile
> Gitpod: use latest edge release

- docs/hello_nextflow/03_hello_gatk.md
- gitpod-ws.code-workspace
> Caught one more set of incorrect file paths

- docs/basic_training/executors.fr.md
- docs/basic_training/executors.md
- docs/basic_training/executors.pt.md
- **Fix #336 baseDir -> projectDir, from -> of**
- **Update docs/troubleshoot/06_exercise.md**
- **Apply suggestions from code review**
- **Apply suggestions from code review**
- **Update mkdocs.yml**
- **Update mkdocs.yml**
- **Update groovy.md**
- **Fix minor typo in Groovy intro**
- **Fixes #340**
> fix awsbatch docs url

- docs/basic_training/containers.md
- docs/basic_training/setup.fr.md
- docs/basic_training/setup.pt.md
- docs/envsetup/index.md
- docs/hands_on/03_setup.md
- docs/hello_nextflow/01_orientation.md
- docs/hello_nextflow/02_hello_world.md
- docs/hello_nextflow/03_hello_gatk.md
- docs/hello_nextflow/04_hello_modules.md
- docs/hello_nextflow/index.md
- docs/index.es.md
- docs/index.fr.md
- docs/index.md
- docs/index.pt.md
- docs/nf_develop/1_01_orientation.md
- docs/nf_develop/1_02_create.md
- hello-nextflow/hello-modules.nf
- **Fix GitHub / Gitpod naming**
- **Fix paths/URLs**
- **Fix typos / improve wording**
- **Add exit instructions to all interactive use of containers**
- **Fix error message**
- **Minor fixes to wording + apply standard to syntax**
- **Add missing step**
> Fixes to the Hello Nextflow training material

- docs/advanced/index.md
- docs/basic_training/index.md
- docs/envsetup/01_setup.md
- docs/envsetup/02_local.md
- docs/hello_nextflow/02_hello_world.md
- docs/hello_nextflow/index.md
- docs/nf_customize/index.md
- docs/nf_develop/index.md
- docs/troubleshoot/index.md
- Added Open in Girtpod buttons to pages
- Added line numbers to hello nextflow
- Added new description at section level
- Added small wording alignments
> Update hello nextflow

- docs/basic_training/containers.md
- Current conda example a bit obtuse
- Use of Seqera Containers is confusing given we've only mentioned Biocontainers
> Be more explicit in the conda env creation, be consistent with Seqera Containers/ Biocontainers

- docs/basic_training/cache_and_resume.md
I tweaked the final part of this session previously, but I think it would benefit from a little exercise to bring the point home.
> Add exercise around the caching example

- docs/basic_training/channels.md
> Fix filename in Channels materials - script is actually snippet.nf

- docs/hello_nextflow/04_hello_modules.md
- hello-nextflow/data/samplesheet.csv
- hello-nextflow/hello-modules.nf
- hello-nextflow/scripts/nextflow.config
Remove unnecessary instruction + restore samplesheet and update intervals list path/extension
> Partial fixes for #389

- docs/hello_nextflow/05_hello_operators.md
> Fix error in Operators instructions

- docs/hello_nextflow/seqera/01_run_with_cli.md
Fixes a config approach that doesn't work after all.
> fix: remove tower_workspace_id from config

- hello-nextflow/hello-modules/nextflow.config
- hello-nextflow/hello-nf-test/nextflow.config
- hello-nextflow/solutions/hello-config/4-nextflow.config
- hello-nextflow/solutions/hello-config/5-nextflow.config
Continuation of https://github.com/nextflow-io/training/pull/469 finding loose remaining cpus = 8
> Drop number of CPUs configured in hello series to 4

- docs/basic_training/orientation.pt.md
- docs/envsetup/01_setup.pt.md
- docs/envsetup/02_local.pt.md
- docs/envsetup/index.pt.md
Per the title!
Also translated the orientation section from the Fundamentals training.
Having the fundamentals training fully in portuguese is already great, but the env setup makes it seem more complete.
> Translate the Environment setup section to Brazilian portuguese

- docs/basic_training/channels.md
- docs/basic_training/operators.md
- docs/basic_training/processes.md
Typos, grammar, punctuation, and a wrong description of a rule
> Various fixes

- .gitignore
- mkdocs.yml
- netlify.toml
Goes together with:
Will tackle these in addition to this PR, the first two are no-code changes.
Will tackle the third once the new deployments are working (can push manually until done).
> Add mike versioning

- docs/nf4_science/genomics/03_modules.md
- mkdocs.yml
- nf4-science/genomics/genomics-3.nf
- nf4-science/genomics/genomics-4.nf
- nf4-science/genomics/nextflow.config
Added a modules component to 'Nexflow for Genomics', needed before adding an nf-test component.
I've intentionally not belaboured the points to much- the basic concepts are now in the new 'Hello Modules' and we don't want to maintain duplicated content in two places.
> Add modules component to 'Nextflow for Genomics'

- docs/hello_nextflow/03_hello_workflow.md
> Fix heading to be h4

- docs/nf4_science/genomics/00_orientation.md
Closes https://github.com/nextflow-io/training/issues/540
* Correct link to https://training.nextflow.io/latest/envsetup/
* Provide correct output of `tree . -L 2` at "/workspaces/training/nf4-science/genomics"
* Fix formatting issue with "The data directory"
> Fix minor issues in 00_orientation.md

- docs/index.md
- docs/nf4_science/index.md
Update the nf4science mini courses index. 
Addresses #545
> Add RNAseq to NF4 Science index

- docs/side_quests/index.md
- docs/side_quests/nf-test.md
- docs/side_quests/workflows_of_workflows.md
- Improved the index page a little
- Tweaked the current quests' titles to not repeat "Side Quest:"
> Improve how Side Quests show up

- docs/nf4_science/genomics/03_modules.md
- docs/nf4_science/genomics/04_testing.md
- nf4-science/genomics/solutions/modules/gatk/haplotypecaller/tests/main.nf.test
- nf4-science/genomics/solutions/modules/gatk/haplotypecaller/tests/main.nf.test.snap
Fixes minor textual issues and some incorrect file paths.
> Fix typos in nf4_science/genomics/03_modules.md and 04_testing.md

- docs/hello_nextflow/06_hello_config.md
> minor numeration fix in in `hello_nextflow/06_hello_config.md`

- docs/side_quests/nf-core.md
Hi,
I just followed the nf-core introduction and noticed some small errors that I have corrected in this PR.
> Some small fixes to the nf-core introduction

- docs/nf4_science/genomics/02_joint_calling.md
- docs/nf4_science/rnaseq/02_single-sample.md
- docs/nf4_science/rnaseq/03_multi-sample.md
- nf4-science/genomics/genomics-3.nf
- nf4-science/genomics/solutions/modules/gatk/jointgenotyping/main.nf
- nf4-science/rnaseq/solutions/modules/fastqc.nf
- nf4-science/rnaseq/solutions/modules/fastqc_pe.nf
- nf4-science/rnaseq/solutions/modules/hisat2_align.nf
- nf4-science/rnaseq/solutions/modules/hisat2_align_pe.nf
- nf4-science/rnaseq/solutions/modules/multiqc.nf
- nf4-science/rnaseq/solutions/modules/trim_galore.nf
- nf4-science/rnaseq/solutions/modules/trim_galore_pe.nf
In the genomics training we are using symlinks in the beginning, but switch to copy mode in the end.
this PR adds symlink usage throughout. It also adds symlink usage the the rnaseq training for consistency sake
> Consistency with using symlink mode

- .devcontainer/codespaces-dev/devcontainer.json
- .devcontainer/devcontainer.json
- .devcontainer/local-dev/devcontainer.json
- .github/workflows/docker-devcontainer.yml
Fixes https://github.com/nextflow-io/training/issues/613 (hopefully)
> Bump NXF_VER to latest stable (25.04.3)

- docs/index.ko.md
- docs/index.md
User flagged that the links to the code for 'other trainings' were broken.
> Minor link fixes

- docs/help.fr.md
- docs/help.md
- docs/index.fr.md
- mkdocs.yml
> Update French translation for the home page

- .github/workflows/docker-devcontainer.yml
Based on [this fix](https://github.com/lejouson/devcontainer-pico-sdk/pull/14/files).
> Fix buildx error when image contains attestation manifest

- docs/basic_training/orientation.md
Rewriting the section "Environment variables in [Orientation Page](https://training.nextflow.io/latest/basic_training/orientation/#environment-variables) "
Addressing issue #491
> Address #491 - Selecting a Nextflow version and Environment variables

- docs/side_quests/index.md
- docs/side_quests/metadata.md
- docs/side_quests/splitting_and_grouping.md
- docs/side_quests/working_with_files.md
- Minor syntax fix
- Move one bit to a note
- Better explain the reasoning for accessing metadata properties at the workflow rather than the process level
- Fixes to capitalisation
- Fixes to side quests index
- Minor highlights fixes etc
> Minor fixes to intermediate content
